chime/urls.py
from django.urls import path
from . import views

app_name = "meeting"
urlpatterns = [
  path("create/", views.MeetingCreateView.as_view(),name="create"),
  path("", views.MeetingListView.as_view(),name="list"),
  path("<str:pk>/", views.MeetingDetailView.as_view(),name="detail"),
  path("start/<str:pk>/", views.MeetingView.as_view(),name="meeting"),
]

chime2_test/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("chime.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)           

chime/models.py
from django.db import models
import uuid
import os
from django.contrib.auth.models import User

class Meeting(models.Model):
  token = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(max_length=50)
  datetime = models.DateTimeField()
  member = models.ManyToManyField(User)
  response = models.JSONField(blank=True, null=True)
  
class Attendee(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    response = models.JSONField(blank=True, null=True)

chime/views.py
from django.views import generic 
from django.urls import reverse_lazy
from boto3 import Session
from .models import Meeting, Attendee
import json
from django.contrib.auth.mixins import LoginRequiredMixin

class MeetingListView(generic.ListView):
  model = Meeting
  template_name = 'meeting/list.html'

class MeetingView(LoginRequiredMixin,generic.TemplateView):
  model = Meeting
  template_name = 'meeting/meeting.html'
  context_object_name = 'chime'

  login_url = '/accounts/login/'
  redirect_field_name = 'redirect_to'

  def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    
    meeting = Meeting.objects.get(pk=self.kwargs['pk'])
    if meeting.response == None:
        meeting.response = use_chime_meeting(meeting.token)
        meeting.save()
        for member in meeting.member.all():
            attendee = Attendee.objects.create(meeting=meeting,user=member)
            attendee.response = use_chime_attendee(meeting.response["Meeting"]["MeetingId"],member.pk)
            attendee.save()

    context['meeting'] = meeting
    try:
        context['attendee'] = Attendee.objects.get(meeting=self.kwargs['pk'],user=self.request.user)
    except:
        context['attendee'] = ""

    return context

class MeetingDetailView(generic.DetailView):
  model = Meeting
  template_name = 'meeting/detail.html'

class MeetingCreateView(generic.CreateView):
  model = Meeting
  template_name = 'meeting/create.html'
  success_url = reverse_lazy('meeting:list')
  fields = ['name','datetime','member']

def use_chime_meeting(token):

    # create session
    session = Session(profile_name="default")
    chime = session.client("chime")

    response = chime.create_meeting(
        ClientRequestToken=str(token),
        MediaRegion='us-east-1'
    )

    return response

def use_chime_attendee(meeting_id,user_id):

    # create session
    session = Session(profile_name="default")
    chime = session.client("chime")

    response = chime.create_attendee(
        MeetingId=str(meeting_id),
        ExternalUserId="user"+str(user_id),
    )

    return response

chime/templates/meeting/create.html
<!DOCTYPE html>
<html>
  <header>
    <title>ミーティング作成ページ</title>
  </header>
  <body>
    <div>ミーティングを作成してください</div>
    <form method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">ミーティング作成</button> 
    </form>
  <body>
</html>

chime/templates/meeting/detail.html
<!DOCTYPE html>
<html>
  <header>
    <title>{{ object.token }}</title>
  </header>
  <body>
    <p>トークン；{{ object.token }}</p>
    <p>ミーティング名：{{ object.name }}</p>
    <p>時間：{{ object.datetime }}</p>
    <p>メンバー:
      {% for m in object.member.all %}
      {{ m.username }},
      {% endfor %}
    </p>
    <p>response:{{ object.response }}</p>

    <a href="{% url 'meeting:meeting' object.token %}">ミーティングを始める</a>
  <body>
</html>

chime/templates/meeting/list.html
{% for meeting in object_list %}
<p>
  <a href="{% url 'meeting:detail' meeting.token %}">{{ meeting.token }} </a>
</p>
{% empty %}
ミーティングがありません
{% endfor %}

<div><a href="{% url 'meeting:create' %}">ミーティングを作成する</a></div>

chime/templates/meeting/meeting.html
{% load static %}
{% load replace %}

<!DOCTYPE html>
<html>
    <head>
        <script src="{% static 'scripts/amazon-chime-sdk.min.js' %}"></script>
    </head>
    
    <body>
        <div>
            <div id="video-tile">
                <video id="video-tile-self"></video>
            </div>
            <audio id="audio-view"></audio>
        </div>
    </body>
    
    <script>
    
        (async () => {
                
            const meeting = JSON.parse(`{{ meeting.response|replace1|safe }}`);
            const attendee = JSON.parse(`{{ attendee.response|replace2|safe }}`);
    
            const logger = new ChimeSDK.ConsoleLogger('ChimeMeetingLogs', ChimeSDK.LogLevel.DEBUG);
            const deviceController = new ChimeSDK.DefaultDeviceController(logger);
            const configuration = new ChimeSDK.MeetingSessionConfiguration(meeting,attendee);
            const meetingSession = new ChimeSDK.DefaultMeetingSession(configuration, logger, deviceController);
    
            try {
            const audioInputs = await meetingSession.audioVideo.listAudioInputDevices();
            const audioOutputs = await meetingSession.audioVideo.listAudioOutputDevices();
            const videoInputs = await meetingSession.audioVideo.listVideoInputDevices();
            await meetingSession.audioVideo.chooseAudioInputDevice(audioInputs[0].deviceId);
            await meetingSession.audioVideo.chooseAudioOutputDevice(audioOutputs[0].deviceId);
            await meetingSession.audioVideo.chooseVideoInputDevice(videoInputs[0].deviceId);
        } catch (err) {
            // handle error - unable to acquire audio device perhaps due to permissions blocking
        }

        const audioOutputElement = document.getElementById('audio-view');
        meetingSession.audioVideo.bindAudioElement(audioOutputElement);

        const videoElementSelf = document.getElementById('video-tile-self');
        const videoElementTile = document.getElementById('video-tile');

        const observer = {
            videoTileDidUpdate: tileState => {

                if (tileState.localTile){
                    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElementSelf);
                }else{
                    if(!document.getElementById(tileState.tileId)){
                        const node = document.createElement("video");
                        node.id = tileState.tileId;
                        videoElementTile.appendChild(node);
                    }
                    const videoElementNew = document.getElementById(tileState.tileId);
                    meetingSession.audioVideo.bindVideoElement(tileState.tileId, videoElementNew);
                }
            },
            videoTileWasRemoved: tileId => {
                if(document.getElementById(tileId)){
                    const videoElementRemoved = document.getElementById(tileId);
                    videoElementRemoved.remove();
                }
            }
        };
        
        meetingSession.audioVideo.addObserver(observer);
        meetingSession.audioVideo.startLocalVideoTile();
        meetingSession.audioVideo.start();
        })();
    </script>
    
    </html>